name: SSE CI/CD
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install dependencies"
        run: pip install pytest coverage numpy matplotlib
      - name: "Run pytest"
        run: python -m pytest
      - name: "Run coverage"
        run: coverage run -m pytest
      - name: "Create .gitignore"
        run: touch .gitignore
      - name: "Add .coverage to .gitignore"
        run: echo .coverage >> .gitignore
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage
          retention-days: 1
  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install dependency"
        run: pip install coverage
      - name: "Download artifact"
        uses: actions/download-artifact@v2
        with:
          name: coverage
      - name: "Generate coverage  report in xml format"
        run: coverage xml
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml
          retention-days: 14